channels:
- conda-forge
dependencies:
- breathe
- catch2 >=3.0.0
- cmake
- doxygen
- furo
- ninja
- numpy
- pybind11
- python
- scikit-build
- setuptools_scm
- sphinx
- xtensor
- xtensor-python >=0.25.2
