channels:
- conda-forge
dependencies:
- catch2
- cmake
- doxygen
- matplotlib
- ninja
- numpy
- pybind11
- python
- scikit-build
- setuptools_scm
- sphinx
- sphinx_rtd_theme
- xtensor
- xtensor-python
